name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
  emoji_picker_flutter: ^1.6.3
  intl: ^0.19.0
  flutter_secure_storage: ^10.0.0
  http: ^1.1.0
  timeago: ^3.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  socket_io_client: ^2.0.3

  http_parser: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

