name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
  emoji_picker_flutter: ^4.4.0
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0
  http: ^1.1.0
  timeago: ^3.6.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  socket_io_client: ^3.1.3

  http_parser: any
  flutter_webrtc: ^1.2.1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

